import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#F2F1EB',
  '--slot4-page-text': '#26352A',
  '--slot4-panel-bg': '#EEE7DA',
  '--slot4-surface-bg': '#F8F7F2',
  '--slot4-muted-text': '#3F5144',
  '--slot4-soft-muted-text': '#526657',
  '--slot4-accent': '#26352A',
  '--slot4-accent-fill': '#88AB8E',
  '--slot4-accent-soft': '#AFC8AD66',
  '--slot4-on-accent': '#F2F1EB',
  '--slot4-on-fill': '#162119',
  '--slot4-dark-bg': '#EEE7DA',
  '--slot4-dark-text': '#162119',
  '--slot4-media-bg': '#EEE7DA',
  '--slot4-cream': '#F2F1EB',
  '--slot4-warm': '#EEE7DA',
  '--slot4-lavender': '#AFC8AD',
  '--slot4-gray': '#D9D4C8',
  '--slot4-body-gradient': 'radial-gradient(circle at 50% -10%, rgba(175,200,173,0.55), transparent 42%), #F2F1EB',
  '--editable-page-bg': '#F2F1EB',
  '--editable-page-text': '#26352A',
  '--editable-container': '1440px',
  '--editable-border': '#88AB8E55',
  '--editable-nav-bg': '#F2F1EB',
  '--editable-nav-text': '#26352A',
  '--editable-nav-active': '#88AB8E',
  '--editable-nav-active-text': '#162119',
  '--editable-cta-bg': '#88AB8E',
  '--editable-cta-text': '#162119',
  '--editable-search-bg': '#F8F7F2',
  '--editable-footer-bg': '#EEE7DA',
  '--editable-footer-text': '#26352A',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-[var(--editable-border)]',
  shadow: 'shadow-[0_1px_0_rgba(38,53,42,0.08)]',
  shadowStrong: 'shadow-[0_24px_70px_rgba(38,53,42,0.14)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(242,241,235,0.08),rgba(38,53,42,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-6 lg:px-8',
    sectionY: 'py-16 sm:py-20 lg:py-[120px]',
  },
  layout: {
    safeGrid: 'grid gap-5 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[260px] shrink-0 snap-start sm:w-[320px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.22em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-normal leading-[1] sm:text-6xl lg:text-[5rem]',
    sectionTitle: 'text-3xl font-normal leading-[1.05] sm:text-5xl lg:text-[4rem]',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-xl border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-xl border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-xl border border-[var(--editable-border)] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-[4px] bg-[var(--slot4-accent-fill)] px-[18px] py-3 text-sm font-semibold text-[var(--slot4-on-fill)] transition duration-[400ms] hover:bg-[var(--slot4-dark-bg)] active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-[4px] border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-[18px] py-3 text-sm font-semibold text-[var(--slot4-page-text)] transition duration-[400ms] hover:border-[var(--slot4-accent)] hover:bg-[var(--slot4-accent-soft)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-[4px] ${editablePalette.accentBg} px-[18px] py-3 text-sm font-semibold text-[var(--slot4-on-fill)] transition duration-[400ms] hover:bg-[var(--slot4-dark-bg)] active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-xl ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
  },
  motion: {
    lift: 'transition duration-[400ms] hover:-translate-y-1 hover:border-[var(--slot4-accent)]/70 hover:shadow-[0_24px_70px_rgba(38,53,42,0.16)]',
    fade: 'transition duration-[400ms] hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Map reference tokens into editableRootStyle first; page JSX consumes variables.',
  'Keep public copy centered on curated bookmarks, collections, and resources.',
  'Use wide readable grids and dark premium resource shelves.',
  'Use postHref() for post links so task routes keep working.',
] as const
